name: Send repository dispatch event

on:

  push:
    branches: [ master, main ]

    # paths-ignore:
    #   - '**/README.md'
    #   - '**.jpg'
    #   - '**.png'

  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    env:
      TARGET_REPOSITORY: "Swarm-Systems-Lab/source_seeking"
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${TARGET_REPOSITORY}/dispatches \
            -d '{"event_type":"dispatch-event"}'